# Generated by Django 2.1 on 2019-05-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saran',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('dari', models.CharField(max_length=24)),
                ('sarans', models.TextField()),
            ],
        ),
    ]
