# Generated by Django 2.2.1 on 2019-05-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saran',
            fields=[
                ('objectid', models.AutoField(primary_key=True, serialize=False)),
                ('dari', models.CharField(max_length=24)),
                ('sarans', models.TextField()),
            ],
        ),
    ]
